export { MCP_OAUTH_AUTHORIZATION_URL_TOOL_UPDATE } from '@cloud-code/protocol';

// Runtime validators for the per-tool `structured` payloads of a tool
// result (see packages/protocol/src/structured.ts) — clients safeParse
// these instead of trusting the loose record.
export {
  agentResultStructuredSchema,
  agentSwarmResultStructuredSchema,
  askUserQuestionStructuredSchema,
  backgroundTaskStructuredSchema,
  exitPlanModeStructuredSchema,
  goalSnapshotStructuredSchema,
  readMediaFileStructuredSchema,
} from '@cloud-code/protocol';

export type {
  AgentEvent,
  AgentStatusUpdatedEvent,
  AssistantDeltaEvent,
  BackgroundTaskStartedEvent,
  BackgroundTaskTerminatedEvent,
  CompactionBlockedEvent,
  CompactionCancelledEvent,
  CompactionCompletedEvent,
  CompactionResult,
  CompactionStartedEvent,
  CronFiredEvent,
  ErrorEvent,
  Event,
  GoalReasonCode,
  GoalUpdatedEvent,
  HookResultEvent,
  MailboxActivityEvent,
  MailboxActivityMessage,
  McpOAuthAuthorizationUrlUpdateData,
  McpServerStatusEvent,
  McpServerStatusPayload,
  PluginCommandActivatedEvent,
  SessionCreatedEvent,
  SessionMetaUpdatedEvent,
  SessionStatusChangedEvent,
  SessionWorkChangedEvent,
  SkillActivatedEvent,
  SubagentCompletedEvent,
  SubagentFailedEvent,
  SubagentSpawnedEvent,
  SubagentStartedEvent,
  SubagentSuspendedEvent,
  TeamMemberWire,
  TeamTaskWire,
  TeamTaskWireStatus,
  TeamUpdatedEvent,
  TeamWire,
  ThinkingDeltaEvent,
  ToolCallDeltaEvent,
  ToolCallStartedEvent,
  ToolInputDisplay,
  ToolListUpdatedEvent,
  ToolListUpdatedReason,
  ToolProgressEvent,
  ToolResultDisplayRef,
  ToolResultEvent,
  ToolResultStructured,
  ToolUpdate,
  TurnEndedEvent,
  TurnEndReason,
  TurnRateLimitPausedEvent,
  TurnRateLimitResumingEvent,
  TurnStartedEvent,
  TurnStepCompletedEvent,
  TurnStepInterruptedEvent,
  TurnStepRetryingEvent,
  TurnStepStartedEvent,
  UsageStatus,
  WarningEvent,
} from '@cloud-code/protocol';

export type { CloudCodeErrorPayload } from '../errors';
